---
- name: Setup VMs
  hosts: all
  serial: 40%
  become: true
  vars_files:
    - /etc/ansible/docker_config.yml

  tasks:
    - name: Install docker
      yum:
        name: docker
        state: latest
  
    - name: Install pip
      yum:
        name: pip
        state: latest

    - name: Enable docker
      service:
        name: docker
        state: started
        enabled: "yes"
    
    - name: Install docker sdk for python
      pip:
        name: docker-py
        state: latest
    
    - name: Login to private registry
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_access_key }}"
      register: login_results

    - name: Deploy app
      docker_container:
        name: app_container
        image: ktoufas/to_do_app:{{ version }}
        state: started
        restart_policy: on-failure
        recreate: yes
        detach: yes
        ports:
          - 80:8080
